
services:
  bot:
    command: ['python', 'bot.py']
    build: .
    volumes:
      - ./images/out/:/app/images/out/
      - ./logs/bot.log:/app/logs/bot.log
  
  main:
    command: ['python', 'main.py', '--noauth_local_webserver']
    build: .
    volumes:
      - ./logs/main.log:/app/logs/main.log
      - ./client_secrets.json:/app/client_secrets.json
  