
services:
  bot:
    command: ['python', 'bot.py']
    build: .
    volumes:
      - ./images/out:/app/images/out
      - ./config:/app/config
      - ./logs:/app/logs
  
  main:
    command: ['python', 'main.py', '--noauth_local_webserver']
    build: .
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
  